### ISSUE TITLE
Improve long names/labels

### ISSUE THREAD

**Issue by oodamien** [spring-projects/spring-flo#80]
![image](https://user-images.githubusercontent.com/487067/91634552-7fe00780-e9f1-11ea-9679-b2de5ef761c9.png)

**Comment by BoykoAlex** [comment]
@sabbyanandan we should transfer this in https://github.com/spring-cloud/spring-cloud-dataflow-ui

@oodamien I only see long not truncated label in the stream name label. The others show up fine for me with master branch...

**Comment by sabbyanandan** [comment]
Hi, @BoykoAlex. Wouldn't be better to fix the tooltop/label and the layout problem in Flo itself? Feel free to move it to the UI backlog, if you think that's where the fix needs to go.

**Comment by BoykoAlex** [comment]
@sabbyanandan I can't move it myself... don't even see spring-cloud org in there.

Flo doesn't have any label truncation logic mainly because label truncation is something one would like to have and the other might oppose by having shape expand to fit a label entirely. It might be useful to have label truncation utility functions in Flo but without a wide audience requesting these utility functions think it is best to have them in a down stream project to make required corrections faster

**Comment by sabbyanandan** [comment]
Yeah, issues cannot be transferred across different ORGs. I will close and open it on the UI backlog.
