### ISSUE TITLE
How to enable constraints at each node to set maxIncomingLinksNumber in new versions

### ISSUE THREAD

**Issue by snv1914** [spring-projects/spring-flo#86]
Hi,

Regarding usage of constraints in metamodel json:

As i have checked 0.5.0 version metadata(metamodel.json) with contstraints
![image](https://user-images.githubusercontent.com/4299134/121187242-7b505580-c885-11eb-976a-e0083ba11418.png)

But when i try to use 0.8.8 version, in metamodel.ts, there are no constraints in json
![image](https://user-images.githubusercontent.com/4299134/121187487-bbafd380-c885-11eb-82e6-b99f2c2d6408.png)

Even i add constraints in json, they are not working.
I would like to use constraints like below in json for each node.
"constraints":{
         "maxOutgoingLinksNumber":1,
         "maxIncomingLinksNumber":1
}

Can someone help to resolve the issue.

**Comment by BoykoAlex** [comment]
Support for constraints on links number has been removed because of its little value. API client can make this support better and tailored to a specific use case.
The demo app in the repo still has support for constraints but implemented on the demo app side rather than flo lib. If there are more than 2 outgoing links from the "source" node then validation markers appears. Implementation details of it are here: https://github.com/spring-projects/spring-flo/blob/main/src/demo/app/editor.ts#L212
If you'd like to forbid user from creating links restricted by the constraints then you can do it here: https://github.com/spring-projects/spring-flo/blob/main/src/demo/app/editor.ts#L65

You can keep constraints in the JSON inside the node's metadata even and then access constraints objects from those methods I outlined above.

So, just one more time methods to add support for constraints:
EditorService class
 -  ` validateLink(context: Flo.EditorContext, cellViewS : dia.ElementView, magnetS : SVGElement, cellViewT : dia.ElementView, magnetT : SVGElement, isSource : boolean, linkView : dia.LinkView)` - restrict links rceation from ports
 - ` validate(graph : dia.Graph, dsl: string, flo: Flo.EditorContext) : Promise<Map<string | number, Flo.Marker[]>>` - to show markers for nodes violating links constraints (see the demo app link above)
